# Generated by Django 5.1.1 on 2025-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='volume_option',
            field=models.CharField(choices=[('50 ml', '50 ml'), ('30 ml', '30 ml'), ('10 ml combo', '10 ml combo')], default='50 ml', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume_option',
            field=models.CharField(choices=[('50 ml', '50 ml'), ('30 ml', '30 ml'), ('10 ml combo', '10 ml combo')], default='50 ml', max_length=20),
        ),
    ]
