# Generated by Django 5.1.1 on 2025-09-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_deliveryfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfeature',
            name='icon',
            field=models.CharField(choices=[('truck', 'Truck (Delivery)'), ('shield', 'Shield (Cash on Delivery)'), ('return', 'Return Arrow')], default='truck', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryfeature',
            name='icon_html',
            field=models.TextField(blank=True, help_text='Deprecated. Use icon picker above.', null=True),
        ),
    ]
