# Generated by Django 5.1.1 on 2025-09-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_deliveryfeature_icon_alter_deliveryfeature_icon_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfeature',
            name='icon_color',
            field=models.CharField(default='#111111', help_text="CSS color, e.g., #111111 or 'black'", max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryfeature',
            name='icon_size',
            field=models.PositiveIntegerField(default=24, help_text='Icon size in pixels'),
        ),
        migrations.AddField(
            model_name='deliveryfeature',
            name='pages',
            field=models.CharField(blank=True, help_text='Comma-separated: all, home, shop, product, cart, checkout, category_male, category_female, category_unisex, search', max_length=200, null=True),
        ),
    ]
