# Generated by Django 5.1.1 on 2025-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_deliveryfeature_icon_color_deliveryfeature_icon_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us', max_length=150)),
                ('content', models.TextField(blank=True, null=True)),
                ('bullet1', models.CharField(blank=True, max_length=120, null=True)),
                ('bullet2', models.CharField(blank=True, max_length=120, null=True)),
                ('bullet3', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_url', models.CharField(default='/shop/view/', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryfeature',
            name='pages',
            field=models.CharField(blank=True, help_text='Comma-separated: all, home, shop, product, cart, checkout, category_male, category_female, category_unisex, search, about, contact, profile, thankyou', max_length=200, null=True),
        ),
    ]
