# Generated by Django 5.1.1 on 2025-09-30 21:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutpage_alter_deliveryfeature_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='layout',
            field=models.CharField(choices=[('image_right', 'Image Right'), ('image_left', 'Image Left')], default='image_right', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
