# Generated by Django 5.1.1 on 2025-10-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutpage_layout_alter_aboutpage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Contact Us', max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, default='We’d love to hear from you', max_length=200, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='contact_images')),
                ('form_enabled', models.BooleanField(default=True)),
                ('form_title', models.CharField(default='Send us a Message', max_length=120)),
                ('form_subtitle', models.CharField(blank=True, default='Our team will get back to you shortly.', max_length=200, null=True)),
                ('thank_you_message', models.TextField(blank=True, default='Thanks for contacting us! We’ll reach out soon.', null=True)),
                ('address', models.CharField(blank=True, default='H-31, Road 4, Block F, Sector 2, Aftabnagar, Dhaka, Bangladesh.', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='+880 1336046969', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='zenkobangladesh@gmail.com', max_length=254, null=True)),
                ('open_hours', models.CharField(blank=True, default='Sunday – Friday, 10:00 AM – 5:00 PM', max_length=120, null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Use a Google Maps embed URL', null=True)),
                ('social_instagram', models.URLField(blank=True, null=True)),
                ('social_facebook', models.URLField(blank=True, null=True)),
                ('social_tiktok', models.URLField(blank=True, null=True)),
                ('social_pinterest', models.URLField(blank=True, null=True)),
                ('newsletter_enabled', models.BooleanField(default=True)),
                ('newsletter_title', models.CharField(default='Stay in the Aroma', max_length=120)),
                ('newsletter_subtitle', models.CharField(blank=True, default='Join our newsletter for exclusive launches and offers.', max_length=200, null=True)),
                ('newsletter_image', models.ImageField(blank=True, help_text='Optional background image', null=True, upload_to='contact_images')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
